version: '3.4'

services:
  pmi.hospital:
    image: ${DOCKER_REGISTRY-}pmihospital
    build:
      context: .
      dockerfile: PMI.Hospital/Dockerfile
    ports:
      - "81:81"
      - "443:443"
    environment:
      - ConnectionStrings__MsSql=Server=db;Database=cHospital;User ID=sa;Password=Your_password123;TrustServerCertificate=True
    depends_on:
      - db
    entrypoint: ["/wait-for-it.sh", "db:1433", "--", "dotnet", "PMI.Hospital.dll"]

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
